#!/bin/bash
cd -
root@64286ed52e8c:~/alx-system_engineering-devops/0x00-shell_basics# em0;276;0cll_basics# cat 10-back
#!/bin/bash
cd -
root@64286ed52e8c:~/alx-system_engineering-devops/0x00-shell_basics# em#!/bin/bash
cd -
